# Generated by Django 2.1.1 on 2018-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSISO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('os_type', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Microsoft Windows'), ('BSD', 'BSD'), ('Unix', 'Unix'), ('MacOS', 'MacOS'), ('Other', 'Other')], default='Linux', max_length=10)),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('iso', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'os_iso',
            },
        ),
    ]
