# Generated by Django 2.1.1 on 2018-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180914_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osiso',
            name='status',
            field=models.CharField(choices=[('FINISHED', '上传完成'), ('UPLOADING', '上传中'), ('WAITING', '等待上传'), ('FAILED', '上传失败')], default='UPLOADING', max_length=10),
        ),
    ]
