# Generated by Django 2.1.1 on 2018-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('conn_type', models.CharField(default='default', max_length=10)),
                ('user', models.CharField(default='root', max_length=32)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('key_file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
    ]
