# Generated by Django 2.1.1 on 2018-09-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField()),
                ('vcpu', models.IntegerField()),
                ('img', models.CharField(blank=True, max_length=128, null=True)),
                ('iso', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'machine_config',
            },
        ),
        migrations.CreateModel(
            name='VMachines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'vmachines',
            },
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='machines.VMachines'),
        ),
    ]
