# Generated by Django 2.1.1 on 2018-09-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20180925_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineconfig',
            name='disk_size',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
