# Generated by Django 2.1.1 on 2018-09-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_vmachines_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineconfig',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='machines.VMachines'),
        ),
    ]
